# docker-compose.yml
# This file sets up two services: 3x-ui and Caddy.
# Caddy will act as a reverse proxy to provide SSL for 3x-ui.

version: "3.8"

services:
  3x-ui:
    # Using the official 3x-ui Docker image
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    restart: unless-stopped
    volumes:
      # Mount a volume for the 3x-ui database to persist data
      - ./3x-ui-db:/etc/x-ui/
    networks:
      - proxy
    # Exposing the default 3x-ui port. Caddy will connect to this internally.
    # You don't need to expose this port to the host machine.
    expose:
      - 2053

  caddy:
    # Using the official Caddy Docker image
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      # Port 80 is used for the initial ACME HTTP-01 challenge for SSL
      - "80:80"
      # Port 443 is for HTTPS traffic
      - "443:443"
    volumes:
      # Mount the Caddyfile for configuration
      - ./Caddyfile:/etc/caddy/Caddyfile
      # Mount a volume for Caddy's data to persist SSL certificates
      - caddy_data:/data
      # Mount a volume for Caddy's configuration
      - caddy_config:/config
    networks:
      - proxy

networks:
  proxy:
    # Create a network for the containers to communicate with each other

volumes:
  caddy_data:
  caddy_config:
