version: '3.8'

services:
  x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: x-ui
    restart: unless-stopped
    volumes:
      - ./x-ui-data:/etc/x-ui
      - ./x-ui-logs:/var/log/x-ui
      - caddy_certs:/etc/caddy/certs:ro
    expose:
      - "2053"
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
      - DOMAIN=${DOMAIN}
    networks:
      - x-ui-network
    command: >
      sh -c "
      echo 'Waiting for Caddy to generate certificates...';
      while [ ! -f /etc/caddy/certs/$${DOMAIN}/$${DOMAIN}.crt ]; do sleep 2; done;
      echo 'Certificates found, starting X-UI...';
      /app/x-ui
      "

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_certs:/etc/caddy/certs
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - x-ui
    networks:
      - x-ui-network

volumes:
  caddy_certs:
  x-ui-data:
  x-ui-logs:

networks:
  x-ui-network:
    driver: bridge
